   <TR>
   <TD COLSPAN=14 BGCOLOR="#0402AC" VALIGN="top">
   <TABLE WIDTH="100%" BORDER="0">
   <TR> <TD COLSPAN=14 VALIGN="middle"><CENTER>
   VNIMANIE ! ZAGRUZKA FAILOV NA SERVER VREMENNO NEDOSTUPNA ! <BR> NA SAITE VEDUTSYa TEHNIChESKIE RABOTY... <BR><BR>
   <!--<B><FONT SIZE=+1 COLOR=LIME>Spasibo za ponimanie !</FONT></B></CENTER>-->
   <BR>
   <CENTER>NO VY PO PREZHNEMU MOZHETE SKACHIVAT' UZHE ZAGRUZHENNYE FAYLY. &nbsp; &nbsp; <BR>
   Prosto pereydite po <A HREF="files.php"><FONT FACE="Times New Roman" SIZE=+2 COLOR=ORANGE>ETOY</FONT></A> ssylke !
   </CENTER></TD> </TR> </TABLE>